/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TrustLockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "adminRefund"
      | "adminRelease"
      | "claimExpiredRefund"
      | "deals"
      | "dispute"
      | "feeBps"
      | "feeRecipient"
      | "lock"
      | "owner"
      | "release"
      | "renounceOwnership"
      | "setFeeBps"
      | "setFeeRecipient"
      | "transferOwnership"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DealDisputed"
      | "DealLocked"
      | "DealRefunded"
      | "DealReleased"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "adminRefund",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "adminRelease",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimExpiredRefund",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "deals", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "dispute", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "feeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lock",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "release", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "adminRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimExpiredRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dispute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lock", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "release", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFeeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace DealDisputedEvent {
  export type InputTuple = [dealId: BytesLike];
  export type OutputTuple = [dealId: string];
  export interface OutputObject {
    dealId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealLockedEvent {
  export type InputTuple = [
    dealId: BytesLike,
    buyer: AddressLike,
    seller: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    dealId: string,
    buyer: string,
    seller: string,
    amount: bigint
  ];
  export interface OutputObject {
    dealId: string;
    buyer: string;
    seller: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealRefundedEvent {
  export type InputTuple = [dealId: BytesLike];
  export type OutputTuple = [dealId: string];
  export interface OutputObject {
    dealId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealReleasedEvent {
  export type InputTuple = [dealId: BytesLike];
  export type OutputTuple = [dealId: string];
  export interface OutputObject {
    dealId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TrustLock extends BaseContract {
  connect(runner?: ContractRunner | null): TrustLock;
  waitForDeployment(): Promise<this>;

  interface: TrustLockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  adminRefund: TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;

  adminRelease: TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;

  claimExpiredRefund: TypedContractMethod<
    [dealId: BytesLike],
    [void],
    "nonpayable"
  >;

  deals: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        buyer: string;
        seller: string;
        amount: bigint;
        fee: bigint;
        status: bigint;
        expiresAt: bigint;
      }
    ],
    "view"
  >;

  dispute: TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;

  feeBps: TypedContractMethod<[], [bigint], "view">;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  lock: TypedContractMethod<
    [
      dealId: BytesLike,
      seller: AddressLike,
      amount: BigNumberish,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  release: TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFeeBps: TypedContractMethod<[_bps: BigNumberish], [void], "nonpayable">;

  setFeeRecipient: TypedContractMethod<
    [_recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "adminRefund"
  ): TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminRelease"
  ): TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimExpiredRefund"
  ): TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deals"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        buyer: string;
        seller: string;
        amount: bigint;
        fee: bigint;
        status: bigint;
        expiresAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "dispute"
  ): TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lock"
  ): TypedContractMethod<
    [
      dealId: BytesLike,
      seller: AddressLike,
      amount: BigNumberish,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "release"
  ): TypedContractMethod<[dealId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeBps"
  ): TypedContractMethod<[_bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[_recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "DealDisputed"
  ): TypedContractEvent<
    DealDisputedEvent.InputTuple,
    DealDisputedEvent.OutputTuple,
    DealDisputedEvent.OutputObject
  >;
  getEvent(
    key: "DealLocked"
  ): TypedContractEvent<
    DealLockedEvent.InputTuple,
    DealLockedEvent.OutputTuple,
    DealLockedEvent.OutputObject
  >;
  getEvent(
    key: "DealRefunded"
  ): TypedContractEvent<
    DealRefundedEvent.InputTuple,
    DealRefundedEvent.OutputTuple,
    DealRefundedEvent.OutputObject
  >;
  getEvent(
    key: "DealReleased"
  ): TypedContractEvent<
    DealReleasedEvent.InputTuple,
    DealReleasedEvent.OutputTuple,
    DealReleasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DealDisputed(bytes32)": TypedContractEvent<
      DealDisputedEvent.InputTuple,
      DealDisputedEvent.OutputTuple,
      DealDisputedEvent.OutputObject
    >;
    DealDisputed: TypedContractEvent<
      DealDisputedEvent.InputTuple,
      DealDisputedEvent.OutputTuple,
      DealDisputedEvent.OutputObject
    >;

    "DealLocked(bytes32,address,address,uint256)": TypedContractEvent<
      DealLockedEvent.InputTuple,
      DealLockedEvent.OutputTuple,
      DealLockedEvent.OutputObject
    >;
    DealLocked: TypedContractEvent<
      DealLockedEvent.InputTuple,
      DealLockedEvent.OutputTuple,
      DealLockedEvent.OutputObject
    >;

    "DealRefunded(bytes32)": TypedContractEvent<
      DealRefundedEvent.InputTuple,
      DealRefundedEvent.OutputTuple,
      DealRefundedEvent.OutputObject
    >;
    DealRefunded: TypedContractEvent<
      DealRefundedEvent.InputTuple,
      DealRefundedEvent.OutputTuple,
      DealRefundedEvent.OutputObject
    >;

    "DealReleased(bytes32)": TypedContractEvent<
      DealReleasedEvent.InputTuple,
      DealReleasedEvent.OutputTuple,
      DealReleasedEvent.OutputObject
    >;
    DealReleased: TypedContractEvent<
      DealReleasedEvent.InputTuple,
      DealReleasedEvent.OutputTuple,
      DealReleasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
